version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false
  cms:
    external: false
  matomo:
    external: false

services:
  # reverse proxy for service lookup
  traefik:
    restart: always
    image: traefik:v2.10
    networks:
      - internal
      - web
    command:
      - --api.dashboard=true
      - --log.level=DEBUG
      - --providers.docker=true
      - --providers.docker.watch=true
      - --providers.docker.network=web
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.lets-encrypt.acme.tlschallenge=true
      - --certificatesresolvers.lets-encrypt.acme.email=${POSTMASTER}
      - --certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`monitor.young-carers-austria.at`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.routers.dashboard.tls.certresolver=lets-encrypt"
      - "traefik.http.middlewares.auth.digestauth.users=${TRAEFIK_USER}:traefik:${TRAEFIK_PASSWORD}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro

  cms:
    image: ghcr.io/bemayr/young-carers-austria.cms:latest
    restart: unless-stopped
    depends_on:
      - cms-database
    labels:
      - traefik.enable=true
      - traefik.http.routers.cms.rule=Host(`redaktion.young-carers-austria.at`)
      - traefik.http.routers.cms.tls=true
      - traefik.http.routers.cms.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
      - cms
    env_file:
      - variables.cms.env

  cms-database:
    image: mongo:6.0.2
    restart: unless-stopped
    networks:
      - cms
    volumes:
      - ./data/cms-database/db:/data/db:rw
      - ./data/cms-database/config:/data/configdb:rw
    env_file:
      - variables.cms-database.env

  linkchecker:
    image: bemayr/lychee2http:latest
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.linkchecker.rule=Host(`linkchecker.young-carers-austria.at`)
      - traefik.http.routers.linkchecker.tls=true
      - traefik.http.routers.linkchecker.tls.certresolver=lets-encrypt
      - traefik.port=80
    command: >
      -form -cgi -no-index -500 -show-errors -port=80 -host="0.0.0.0"
      /check 'echo $$v_content | /usr/local/bin/lychee - --format=json --no-progress --verbose | xargs -0 printf \"Content-Type: application/json\n\n%s\"'
      /check-content '/usr/local/bin/lychee https://redaktion.young-carers-austria.at/api/v1/content --no-progress'
    expose: [80]
    networks:
      - web
      - internal
      - cms

  chatbot:
    image: ghcr.io/bemayr/young-carers-austria.chatbot:latest
    restart: always
    depends_on:
      - cms
    labels:
      - traefik.enable=true
      - traefik.http.routers.chatbot.rule=Host(`chatbot.young-carers-austria.at`)
      - traefik.http.routers.chatbot.tls=true
      - traefik.http.routers.chatbot.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    environment:
      - CMS_URL=${CMS_URL}
      - INSIGHTS_URL=${INSIGHTS_URL}
      - INSIGHTS_PAGE_ID=${CHATBOT_INSIGHTS_PAGE_ID}

  app-forward:
    image: bemayr/app-forward:1.0.1
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.app-forward.rule=Host(`app.young-carers-austria.at`)
      - traefik.http.routers.app-forward.tls=true
      - traefik.http.routers.app-forward.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    environment:
      - APPFORWARD_IOSURL=https://apps.apple.com/us/app/young-carers-austria/id1594317016
      - APPFORWARD_ANDROIDURL=https://play.google.com/store/apps/details?id=at.sozialministerium.youngcarers
      - APPFORWARD_FALLBACKURL=https://www.young-carers-austria.at/app/

  web-staging:
    image: ghcr.io/bemayr/young-carers-austria.website:staging
    restart: always
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-staging.rule=Host(`testing.young-carers-austria.at`)
      - traefik.http.routers.web-staging.tls=true
      - traefik.http.routers.web-staging.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web

  insights:
    image: matomo
    restart: always
    depends_on:
      - insights-database
    labels:
      - traefik.enable=true
      - traefik.http.routers.insights.rule=Host(`insights.young-carers-austria.at`)
      - traefik.http.routers.insights.tls=true
      - traefik.http.routers.insights.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./data/insights/config:/var/www/html/config
      - ./data/insights/logs:/var/www/html/logs
      - ./data/insights/matomo:/var/www/html
    networks:
      - matomo
      - internal
      - web
    env_file:
      - variables.insights.env

  insights-database:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - ./data/insights-database/db:/var/lib/mysql:rw
    networks:
      - matomo
    env_file:
      - variables.insights.env
