version: "3"

networks:
  web:
    external: true
  internal:
    external: false
  cms:
    external: false

services:
  cms:
    image: bemayr/young-carers-austria-cms:1.0.0
    container_name: cms
    restart: always
    depends_on:
      - cms-database
    labels:
      - traefik.http.routers.cms.rule=Host(`redaktion.young-carers-austria.at`)
      - traefik.http.routers.cms.tls=true
      - traefik.http.routers.cms.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
      - cms
    env_file:
      - cms.variables.env

  cms-database:
    image: mongo:6.0.2
    container_name: cms-database
    restart: unless-stopped
    networks:
      - cms
    ports:
      - '27017:27017'
    volumes:
      - ./data/cms-database/db:/data/db:rw
      - ./data/cms-database/config:/data/configdb:rw
    env_file:
      - cms-database.variables.env

  app-forward:
    image: bemayr/app-forward:1.0.1
    container_name: app-forward
    restart: always
    labels:
      - traefik.http.routers.app-forward.rule=Host(`app.young-carers-austria.at`)
      - traefik.http.routers.app-forward.tls=true
      - traefik.http.routers.app-forward.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    env_file:
      - app-forward.variables.env
