version: "3.8"

networks:
  web:
    external: true
  internal:
    external: false
  cms:
    external: false
  matomo:
    external: false

services:
  # reverse proxy for service lookup
  traefik:
    restart: always
    image: traefik:v2.9
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.lets-encrypt.acme.tlschallenge=true
      - --certificatesresolvers.lets-encrypt.acme.email=${POSTMASTER}
      - --certificatesresolvers.lets-encrypt.acme.storage=/letsencrypt/acme.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`monitor.young-carers-austria.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.digestauth.users=${TRAEFIK_USER}:traefik:${TRAEFIK_PASSWORD}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    env_file:
      - variables.reverse-proxy.env

  cms:
    image: bemayr/young-carers-austria-cms:1.0.8
    container_name: cms
    restart: unless-stopped
    depends_on:
      - cms-database
    labels:
      - traefik.http.routers.cms.rule=Host(`redaktion.young-carers-austria.at`)
      - traefik.http.routers.cms.tls=true
      - traefik.http.routers.cms.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
      - cms
    env_file:
      - variables.cms.env

  cms-database:
    image: mongo:6.0.2
    container_name: cms-database
    restart: unless-stopped
    networks:
      - cms
    volumes:
      - ./data/cms-database/db:/data/db:rw
      - ./data/cms-database/config:/data/configdb:rw
    env_file:
      - variables.cms-database.env

  linkchecker:
    image: bemayr/lychee2http:latest
    command: "-form -cgi -no-index -500 -port=80 /check 'echo $$v_content | /usr/local/bin/lychee - --format=json --no-progress --verbose | xargs -0 printf \"Content-Type: application/json\n\n%s\"'"
    networks:
      - cms

  chatbot:
    image: bemayr/young-carers-austria-chatbot:1.0.5
    container_name: chatbot
    restart: always
    labels:
      - traefik.http.routers.chatbot.rule=Host(`chatbot.young-carers-austria.at`)
      - traefik.http.routers.chatbot.tls=true
      - traefik.http.routers.chatbot.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    env_file:
      - variables.chatbot.env

  app-forward:
    image: bemayr/app-forward:1.0.1
    container_name: app-forward
    restart: always
    labels:
      - traefik.http.routers.app-forward.rule=Host(`app.young-carers-austria.at`)
      - traefik.http.routers.app-forward.tls=true
      - traefik.http.routers.app-forward.tls.certresolver=lets-encrypt
      - traefik.port=80
    networks:
      - internal
      - web
    environment:
      APPFORWARD_IOSURL=https://apps.apple.com/us/app/young-carers-austria/id1594317016
      APPFORWARD_ANDROIDURL=https://play.google.com/store/apps/details?id=at.sozialministerium.youngcarers
      APPFORWARD_FALLBACKURL=https://www.young-carers-austria.at/app/

  insights:
    image: matomo
    container_name: insights
    restart: always
    depends_on:
      - insights-database
    labels:
      - traefik.http.routers.insights.rule=Host(`insights.young-carers-austria.at`)
      - traefik.http.routers.insights.tls=true
      - traefik.http.routers.insights.tls.certresolver=lets-encrypt
      - traefik.port=80
    volumes:
      - ./data/insights/config:/var/www/html/config
      - ./data/insights/logs:/var/www/html/logs
      - ./data/insights/matomo:/var/www/html
    networks:
      - matomo
      - internal
      - web
    env_file:
      - variables.insights.env

  insights-database:
    image: mariadb
    container_name: insights-database
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - ./data/insights-database/db:/data/db:rw
    networks:
      - matomo
    env_file:
      - variables.insights.env
