/* tslint:disable */
/**
 * This file was automatically generated by Payload CMS.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-accessibility".
 */
export interface Barrierefreiheitserklarung {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-copyright".
 */
export interface Copyright {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-gdpr".
 */
export interface Datenschutzerklarung {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-imprint".
 */
export interface Impressum {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "app-welcome".
 */
export interface Willkommensnachricht {
  id: string;
  hello: {
    [k: string]: unknown;
  }[];
  info: {
    [k: string]: unknown;
  }[];
  feedback: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-messages".
 */
export interface Nachrichten {
  id: string;
  welcome: {
    choices: {
      messages: {
        message: {
          [k: string]: unknown;
        }[];
        id?: string;
      }[];
      id?: string;
    }[];
  };
  'no-result-found': {
    choices: {
      messages: {
        message: {
          [k: string]: unknown;
        }[];
        id?: string;
      }[];
      id?: string;
    }[];
  };
  'results-found': {
    choices: {
      messages: {
        message: {
          [k: string]: unknown;
        }[];
        id?: string;
      }[];
      id?: string;
    }[];
  };
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq".
 */
export interface FAQ {
  id: string;
  entries: {
    question: string;
    answer: {
      [k: string]: unknown;
    }[];
    showOnLandingPage: boolean;
    id?: string;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "emergency".
 */
export interface ImNotfall {
  id: string;
  numbers: {
    label: string;
    number: string;
    id?: string;
  }[];
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-accessibility".
 */
export interface Barrierefreiheitserklarung1 {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-copyright".
 */
export interface Copyright1 {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-gdpr".
 */
export interface Datenschutzerklarung1 {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "website-imprint".
 */
export interface Impressum1 {
  id: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Kategorie {
  id: string;
  name: string;
  heading: string;
  description: {
    [k: string]: unknown;
  }[];
  keywords?: string;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "references".
 */
export interface Referenz {
  id: string;
  address: string;
  title: string;
  description: string;
  image: string;
  showOnLandingPage: boolean;
  keywords?: string;
  source: string | Quelle;
  categories: string[] | Kategorie[];
  opengraph: {};
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Quelle {
  id: string;
  name: string;
  homepage: string;
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "alltagssituationen".
 */
export interface Alltagssituation {
  id: string;
  name: string;
  content: {
    [k: string]: unknown;
  }[];
  _status?: 'draft' | 'published';
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-emojis".
 */
export interface Emoji {
  id: string;
  emoji: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chatbot-names".
 */
export interface Name {
  id: string;
  name: string;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  email?: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  loginAttempts?: number;
  lockUntil?: string;
  createdAt: string;
  updatedAt: string;
}
