version: '3.8'
services:
  cms:
    image: bemayr/young-carers-austria-cms
    container_name: cms
    ports:
      - 80:3000
    volumes:
      - ./database:/app/database
    environment:
      - GITHUB_ACTIONS_TOKEN
      - SESSION_SECRET
