name: (cms) Run the Linkchecker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *' # Run the Linkchecker at 03:00am UTC so that it is finished at 05:00am CEST

jobs:
  run-linkchecker:
    runs-on: ubuntu-latest
    steps:
      - name: Check Links 🖇️
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://redaktion.young-carers-austria.at/links/validate'
          method: 'POST'
          timeout: 60000
