name: (github) Delete Unnecessary Workflow Runs
on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # Delete Workflows every Sunday

jobs:
  delete_cleanup_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: "(github) Delete Unnecessary Workflow Runs"
          retain_days: 0
          keep_minimum_runs: 0
  delete_linkchecker_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          delete_workflow_pattern: "(cms) Run the Linkchecker"
          delete_run_by_conclusion_pattern: success
          retain_days: 7
          keep_minimum_runs: 7
